In [ ]:
import torch as tc
import torch.nn as nn
import numpy as np
import torch

In [ ]:
class MP_Neuron(nn.Module):
  def __init__(self, ):
    super().__init__()
    self.weights=tc.tensor([1, -1])
    self.bias = 0
    self.threshold = 1

  def forward(self, x):
    net_input = tc.sum((self.weights*x)) + self.bias
    return tc.where(net_input>=self.threshold, tc.tensor(1.0), tc.tensor(0.0))

In [ ]:
data=[
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
]

mp = MP_Neuron()

for i in tc.tensor(data):
  print(i,mp(i))

tensor([0, 0]) tensor(0.)
tensor([0, 1]) tensor(0.)
tensor([1, 0]) tensor(1.)
tensor([1, 1]) tensor(0.)


In [ ]:
class XOR_N(nn.Module):
  def __init__(self, ):
    super().__init__()
    self.lin1 = nn.Linear(2, 2)
    self.sig = nn.Sigmoid()
    self.lin2 = nn.Linear(2, 1)
  def forward(self, x):
    x = self.lin1(x)
    x = self.sig(x)
    x = self.lin2(x)
    return x

In [ ]:
model = XOR_N()

In [ ]:
epochs = 1000
mseloss = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr = 0.03)

In [ ]:
data2=[0,1,1,0]

In [ ]:
X = tc.tensor([
    [0.0, 0.0],
    [0.0, 1.0],
    [1.0, 0.0],
    [1.0, 1.0]
])

Y = tc.tensor([0.0,1.0,1.0,0.0]).view(-1,1)

In [ ]:
epochs = 1000

for epoch in range(epochs):
  for i in range(4):

    optimizer.zero_grad()

    yhat = model(X[i])

    loss = mseloss(yhat, Y[i])

    loss.backward()

    optimizer.step()

    if epoch%100==0:
      print(f"loss = {loss}")

loss = 0.00040913213160820305
loss = 1.0244189500808716
loss = 0.7066877484321594
loss = 0.027497751638293266
loss = 0.25197428464889526
loss = 0.2807869017124176
loss = 0.22387844324111938
loss = 0.25392115116119385
loss = 0.11142511665821075
loss = 0.20093730092048645
loss = 0.00245196046307683
loss = 0.0555727444589138
loss = 0.0007876791059970856
loss = 0.00032074260525405407
loss = 6.957693130971165e-06
loss = 1.0053457799585885e-06
loss = 5.931396174219117e-08
loss = 2.034443369325345e-08
loss = 4.916387297271285e-10
loss = 3.197442310920451e-12
loss = 2.589928271845565e-12
loss = 1.2825296380469808e-12
loss = 8.881784197001252e-14
loss = 4.3520742565306136e-14
loss = 1.566746732351021e-12
loss = 9.094947017729282e-13
loss = 5.684341886080802e-14
loss = 7.993605777301127e-15
loss = 1.0267342531733448e-12
loss = 5.115907697472721e-13
loss = 1.4210854715202004e-14
loss = 3.552713678800501e-15
loss = 5.551115123125783e-13
loss = 3.552713678800501e-13
loss = 1.4210854715202004e-14
lo

In [ ]:
print("{:.10f}".format(float(model(tc.tensor([0.0,1.0]))[0].detach().numpy())))
# print("{:.10f}".format(1.0e-05))
# float(tc.tensor(0).numpy())